import './globals.css'
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next"
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Hydrate from './components/Hydrate';
import {Roboto, Lobster} from "next/font/google";

const roboto = Roboto({weight: ['400', '500', '700'], subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

const session = await getServerSession(authOptions);

  return (
    <html className={` ${roboto.className}`} lang="en">
        <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
        </Hydrate>
    </html>
  )
}
